# Generated by Django 2.2.5 on 2019-09-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('cedula_medico', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=15)),
                ('domicilio', models.TextField()),
                ('especialidad', models.CharField(max_length=60)),
                ('correo_electronico', models.EmailField(max_length=255)),
                ('celular', models.CharField(max_length=20)),
            ],
        ),
    ]
