# Generated by Django 2.2.5 on 2019-11-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_auto_20191028_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(max_length=20),
        ),
    ]
