# Generated by Django 2.2.5 on 2019-11-11 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_auto_20191107_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='correo_electronico',
        ),
    ]
