# Generated by Django 2.2.5 on 2019-09-29 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='especialidad',
        ),
    ]
