# Generated by Django 2.2.5 on 2019-11-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='even',
            field=models.CharField(blank='true', choices=[('1.9', 'Mis padres han sido portadores del VIH'), ('1.4', 'He compartido jeringas para el uso de drogas'), ('1.8', 'He recibido una trasfusion sanguinea'), ('94.8', 'He mantenido relaciones sexuales sin proteccion')], max_length=15),
        ),
        migrations.AlterField(
            model_name='home',
            name='infecciones',
            field=models.CharField(blank='true', choices=[('Z1', 'Candidiasis'), ('Z2', 'Citomegalovirus'), ('Z3', 'Cryptosporidiasis'), ('Z4', 'Hepatitis'), ('Z5', 'Herpes'), ('Z6', 'Salmonella'), ('Z7', 'Otra infeccion bacteriana')], max_length=15),
        ),
        migrations.AlterField(
            model_name='home',
            name='manifestaciones',
            field=models.CharField(blank='true', choices=[('x1', 'Fiebre'), ('x2', 'Perdida de peso'), ('x3', 'Dificultades visuales'), ('x4', 'Afecciones respiratorias'), ('x5', 'Diarrea'), ('x6', 'Ulceras orales'), ('x7', 'Lesiones o erupciones cutaneas')], max_length=15),
        ),
        migrations.AlterField(
            model_name='home',
            name='neoplasias',
            field=models.CharField(blank='true', choices=[('n1', 'Sarcoma de Kaposi'), ('n2', 'Linfoma cerebral primario'), ('n3', 'Enfermedad de Hodgkin'), ('n4', 'Cancer cervicouterno'), ('n5', 'Adenocarcinoma')], max_length=15),
        ),
        migrations.AlterField(
            model_name='home',
            name='situacion',
            field=models.CharField(blank='true', choices=[('y1', 'Cuento con pareja sesxual estable'), ('y2', 'No tengo una pareja sexual estable'), ('y3', 'Fui victima de un abuso sexual'), ('y4', 'Soy trabajador(a) sexual')], max_length=15),
        ),
    ]
