# Generated by Django 2.2.5 on 2019-09-29 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pruebaPCR', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id_expediente', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField()),
                ('documento', models.FileField(upload_to='documentos/')),
                ('id_cuestionario', models.ForeignKey(null=True, on_delete=models.SET(0), related_name='cuestionarios_rel', to='pruebaPCR.Prueba_PCR')),
                ('id_prueba', models.ForeignKey(null=True, on_delete=models.SET(0), related_name='pruebas_rel', to='pruebaPCR.Prueba_PCR')),
                ('nss_paciente', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
    ]
