# Generated by Django 2.2.5 on 2019-11-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='documento',
        ),
    ]
