# Generated by Django 2.2.5 on 2019-11-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0002_remove_expediente_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='id_cuestionario',
            field=models.ForeignKey(null=True, on_delete=models.SET(0), related_name='cuestionarios_rel', to='cuestionario.Cuestionario'),
        ),
    ]
