# Generated by Django 2.2.5 on 2019-11-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0003_auto_20191111_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='id_cuestionario',
            field=models.ForeignKey(null=True, on_delete=models.SET(0), related_name='cuestionarios_rel', to='home.Home'),
        ),
    ]
