# Generated by Django 2.2.5 on 2019-09-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id_cuestionario', models.AutoField(primary_key=True, serialize=False)),
                ('nss', models.CharField(max_length=11, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('domicilio', models.TextField()),
                ('estado_civil', models.CharField(max_length=20)),
                ('residencia', models.CharField(choices=[('Aguas Calientes', 'Aguas Calientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Ciudad de México', 'Ciudad de México'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Estado de México', 'Estado de México'), ('Michoacan', 'Michoacan'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo Leon', 'Nuevo Leon'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Queretaro', 'Queretaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatan', 'Yucatan'), ('Zacatecas', 'Zacatecas'), ('No especificado', 'No especificado')], max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('nss_paciente', models.OneToOneField(null=True, on_delete=models.SET(0), related_name='pacientes_rel', to='paciente.Paciente')),
            ],
        ),
    ]
