# Generated by Django 2.2.5 on 2019-09-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuestionario',
            name='nss_paciente',
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='edad',
            field=models.CharField(choices=[('Menos de 1 año', 'Menos de 1 año'), ('1-4', '1-4'), ('5-9', '5-9'), ('10-14', '10-14'), ('15-19', '15-19'), ('20-24', '20-24'), ('25-29', '25-29'), ('30-34', '30-34'), ('35-39', '35-39'), ('40-44', '40-44'), ('45-49', '45-49'), ('50-54', '50-54'), ('55-59', '55-59'), ('60-64', '60-64'), ('Mayor a 65', 'Mayor a 65')], max_length=15),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='estado_civil',
            field=models.CharField(choices=[('Casado', 'Casado'), ('Soltero', 'Sotero'), ('Viudo', 'Viudo'), ('Divorceado', 'Divorceado'), ('Union libre', 'Union Libre')], max_length=15),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='sexo',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=15),
        ),
    ]
