# Generated by Django 2.2.5 on 2019-11-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0003_auto_20191028_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='vacuna',
            field=models.ManyToManyField(blank=True, to='cuestionario.Vacuna'),
        ),
    ]
