# Generated by Django 2.2.5 on 2019-11-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0004_auto_20191111_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuestionario',
            name='vacuna',
        ),
        migrations.DeleteModel(
            name='Vacuna',
        ),
    ]
