# Generated by Django 2.2.5 on 2019-09-29 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba_PCR',
            fields=[
                ('id_prueba', models.AutoField(primary_key=True, serialize=False)),
                ('cadena_PCR', models.TextField()),
                ('resultado', models.IntegerField(blank=True)),
                ('nss_paciente', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
    ]
