# Generated by Django 2.2.5 on 2019-11-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaPCR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba_pcr',
            name='cadena_PCR',
            field=models.CharField(max_length=8),
        ),
    ]
